{
  "openapi": "3.0.0",
  "info": {
    "title": "Brasil API",
    "description": "Acesso programático de informações é algo fundamental na comunicação entre sistemas mas, para nossa surpresa, uma informação tão útil e pública quanto um CEP não consegue ser acessada diretamente por um navegador por conta da API dos Correios não possuir CORS habilitado.\nDado a isso, este projeto experimental tem como objetivo centralizar e disponibilizar endpoints modernos com baixíssima latência utilizando tecnologias como Vercel Smart CDN responsável por fazer o cache das informações em atualmente 23 regiões distribuídas ao longo do mundo (incluindo Brasil). Então não importa o quão devagar for a fonte dos dados, nós queremos disponibilizá-la da forma mais rápida e moderna possível.\n\nRecursos disponíveis\n  - CEP\n  - DDD\n",
    "termsOfService": "https://brasilapi.com.br/",
    "version": "1.0.0",
    "contact": {
      "url": "https://brasilapi.com.br"
    },
    "license": {
      "name": "MIT",
      "url": "https://github.com/BrasilAPI/BrasilAPI/blob/master/LICENSE"
    }
  },
  "tags": [
    {
      "name": "Brasil API",
      "description": "Transformando o Brasil em uma API",
      "externalDocs": {
        "description": "Saiba mais",
        "url": "https://brasilapi.com.br/"
      }
    },
    {
      "name": "CPTEC",
      "description": "Abstração e normalização de dados provenientes da CPTEC"
    }
  ],
  "servers": [
    {
      "url": "https://brasilapi.com.br/api"
    }
  ],
  "paths": {
    "/cnpj/v1/{cnpj}": {
      "get": {
        "tags": ["CNPJ"],
        "summary": "Busca por CNPJ na API Minha Receita.",
        "description": "",
        "parameters": [
          {
            "name": "cnpj",
            "description": "O Cadastro Nacional da Pessoa Jurídica é um número único que identifica uma pessoa jurídica e outros tipos de arranjo jurídico sem personalidade jurídica junto à Receita Federal.\n",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "cnpj": "19131243000197",
                  "identificador_matriz_filial": 1,
                  "descricao_matriz_filial": "Matriz",
                  "razao_social": "OPEN KNOWLEDGE BRASIL",
                  "nome_fantasia": "REDE PELO CONHECIMENTO LIVRE",
                  "situacao_cadastral": 2,
                  "descricao_situacao_cadastral": "Ativa",
                  "data_situacao_cadastral": "2013-10-03",
                  "motivo_situacao_cadastral": 0,
                  "nome_cidade_exterior": null,
                  "codigo_natureza_juridica": 3999,
                  "data_inicio_atividade": "2013-10-03",
                  "cnae_fiscal": 9430800,
                  "cnae_fiscal_descricao": "Atividades de associações de defesa de direitos sociais",
                  "descricao_tipo_logradouro": "ALAMEDA",
                  "logradouro": "FRANCA",
                  "numero": "144",
                  "complemento": "APT   34",
                  "bairro": "JARDIM PAULISTA",
                  "cep": 1422000,
                  "uf": "SP",
                  "codigo_municipio": 7107,
                  "municipio": "SAO PAULO",
                  "ddd_telefone_1": "11  23851939",
                  "ddd_telefone_2": null,
                  "ddd_fax": null,
                  "qualificacao_do_responsavel": 10,
                  "capital_social": 0.0,
                  "porte": 5,
                  "descricao_porte": "Demais",
                  "opcao_pelo_simples": false,
                  "data_opcao_pelo_simples": null,
                  "data_exclusao_do_simples": null,
                  "opcao_pelo_mei": false,
                  "situacao_especial": null,
                  "data_situacao_especial": null,
                  "cnaes_secundarios": [
                    {
                      "codigo": 9493600,
                      "descricao": "Atividades de organizações associativas ligadas à cultura e à arte"
                    },
                    {
                      "codigo": 9499500,
                      "descricao": "Atividades associativas não especificadas anteriormente"
                    },
                    {
                      "codigo": 8599699,
                      "descricao": "Outras atividades de ensino não especificadas anteriormente"
                    },
                    {
                      "codigo": 8230001,
                      "descricao": "Serviços de organização de feiras, congressos, exposições e festas"
                    },
                    {
                      "codigo": 6204000,
                      "descricao": "Consultoria em tecnologia da informação"
                    }
                  ],
                  "qsa": [
                    {
                      "identificador_de_socio": 2,
                      "nome_socio": "NATALIA PASSOS MAZOTTE CORTEZ",
                      "cnpj_cpf_do_socio": "***059967**",
                      "codigo_qualificacao_socio": 10,
                      "percentual_capital_social": 0,
                      "data_entrada_sociedade": "2019-02-14",
                      "cpf_representante_legal": null,
                      "nome_representante_legal": null,
                      "codigo_qualificacao_representante_legal": null
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "CNPJ não encontrado na API Minha Receita.",
            "content": {
              "application/json": {
                "example": {
                  "name": "CnpjPromiseError",
                  "message": "Erro retornado pela API Minha Receita.",
                  "type": "service_error",
                  "errors": [
                    { "message": "CNPJ 00.000.000/0001-91 não encontrado." }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/cep/v1/{cep}": {
      "get": {
        "tags": [
          "CEP"
        ],
        "summary": "Busca por CEP com múltiplos providers de fallback.",
        "description": "",
        "parameters": [
          {
            "name": "cep",
            "description": "O CEP (Código de Endereçamento Postal) é um sistema de códigos que visa racionalizar o processo de encaminhamento e entrega de correspondências através da divisão do país em regiões postais. ... Atualmente, o CEP é composto por oito dígitos, cinco de um lado e três de outro. Cada algarismo do CEP possui um significado.\n",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "cep": "89010025",
                  "state": "SC",
                  "city": "Blumenau",
                  "neighborhood": "Centro",
                  "street": "Rua Doutor Luiz de Freitas Melro"
                }
              }
            }
          },
          "404": {
            "description": "Todos os serviços de CEP retornaram erro.",
            "content": {
              "application/json": {
                "example": {
                  "name": "CepPromiseError",
                  "message": "Todos os serviços de CEP retornaram erro.",
                  "type": "service_error",
                  "errors": [
                    {
                      "name": "ServiceError",
                      "message": "CEP INVÁLIDO",
                      "service": "correios"
                    },
                    {
                      "name": "ServiceError",
                      "message": "CEP não encontrado na base do ViaCEP.",
                      "service": "viacep"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/cep/v2/{cep}": {
      "get": {
        "tags": [
          "CEP v2"
        ],
        "summary": "Busca por CEP com múltiplos providers de fallback v2.",
        "description": "",
        "parameters": [
          {
            "name": "cep",
            "description": "O CEP (Código de Endereçamento Postal) é um sistema de códigos que visa racionalizar o processo de encaminhamento e entrega de correspondências através da divisão do país em regiões postais. ... Atualmente, o CEP é composto por oito dígitos, cinco de um lado e três de outro. Cada algarismo do CEP possui um significado.\n",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "cep": "89010025",
                  "state": "SC",
                  "city": "Blumenau",
                  "neighborhood": "Centro",
                  "street": "Rua Doutor Luiz de Freitas Melro"
                }
              }
            }
          },
          "404": {
            "description": "Todos os serviços de CEP retornaram erro.",
            "content": {
              "application/json": {
                "example": {
                  "name": "CepPromiseError",
                  "message": "Todos os serviços de CEP retornaram erro.",
                  "type": "service_error",
                  "errors": [
                    {
                      "name": "ServiceError",
                      "message": "CEP INVÁLIDO",
                      "service": "correios"
                    },
                    {
                      "name": "ServiceError",
                      "message": "CEP não encontrado na base do ViaCEP.",
                      "service": "viacep"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/ddd/v1/{ddd}": {
      "get": {
        "tags": [
          "DDD"
        ],
        "summary": "Retorna estado e lista de cidades por DDD",
        "description": "",
        "parameters": [
          {
            "name": "ddd",
            "description": "DDD significa Discagem Direta à Distância. É um sistema de ligação telefônica automática entre diferentes áreas urbanas nacionais. O DDD é um código constituído por 2 dígitos que identificam as principais cidades do país e devem ser adicionados ao nº de telefone, juntamente com o código da operadora.\n",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example":
                {
                  "state": "SP",
                  "cities": [
                    "EMBU",
                    "VÁRZEA PAULISTA",
                    "VARGEM GRANDE PAULISTA",
                    "VARGEM",
                    "TUIUTI",
                    "TABOÃO DA SERRA",
                    "SUZANO",
                    "SÃO ROQUE",
                    "SÃO PAULO",
                    "SÃO LOURENÇO DA SERRA",
                    "SÃO CAETANO DO SUL",
                    "SÃO BERNARDO DO CAMPO",
                    "SANTO ANDRÉ",
                    "SANTANA DE PARNAÍBA",
                    "SANTA ISABEL",
                    "SALTO",
                    "SALESÓPOLIS",
                    "RIO GRANDE DA SERRA",
                    "RIBEIRÃO PIRES",
                    "POÁ",
                    "PIRAPORA DO BOM JESUS",
                    "PIRACAIA",
                    "PINHALZINHO",
                    "PEDRA BELA",
                    "OSASCO",
                    "NAZARÉ PAULISTA",
                    "MORUNGABA",
                    "MOGI DAS CRUZES",
                    "MAUÁ",
                    "MAIRIPORÃ",
                    "MAIRINQUE",
                    "JUQUITIBA",
                    "JUNDIAÍ",
                    "JOANÓPOLIS",
                    "JARINU",
                    "JANDIRA",
                    "ITUPEVA",
                    "ITU",
                    "ITATIBA",
                    "ITAQUAQUECETUBA",
                    "ITAPEVI",
                    "ITAPECERICA DA SERRA",
                    "IGARATÁ",
                    "GUARULHOS",
                    "GUARAREMA",
                    "FRANCO DA ROCHA",
                    "FRANCISCO MORATO",
                    "FERRAZ DE VASCONCELOS",
                    "EMBU-GUAÇU",
                    "DIADEMA",
                    "COTIA",
                    "CARAPICUÍBA",
                    "CAMPO LIMPO PAULISTA",
                    "CAJAMAR",
                    "CAIEIRAS",
                    "CABREÚVA",
                    "BRAGANÇA PAULISTA",
                    "BOM JESUS DOS PERDÕES",
                    "BIRITIBA-MIRIM",
                    "BARUERI",
                    "ATIBAIA",
                    "ARUJÁ",
                    "ARAÇARIGUAMA",
                    "ALUMÍNIO"
                  ]
                }
              }
            }
          },
          "404": {
            "description": "DDD não encontrado",
            "content": {
              "application/json": {
                "example":
                {
                  "name": "ddd_error",
                  "message": "DDD não encontrado",
                  "type": "DDD_NOT_FOUND"
                }
              }
            }
          },
          "500": {
            "description": "Todos os serviços de DDD retornaram erro.",
            "content": {
              "application/json": {
                "example":
                {
                  "name": "ddd_error",
                  "message": "Todos os serviços de DDD retornaram erro.",
                  "type": "service_error"
                }
              }
            }
          }
        }
      }
    },
    "/banks/v1": {
      "get": {
        "tags": [
          "BANKS"
        ],
        "summary": "Retorna informações de todos os bancos do Brasil",
        "description": "",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": [
                  {
                    "ispb": "00000000",
                    "name": "BCO DO BRASIL S.A.",
                    "code": 1,
                    "fullName": "Banco do Brasil S.A."
                  },
                  {
                    "ispb": "00000208",
                    "name": "BRB - BCO DE BRASILIA S.A.",
                    "code": 70,
                    "fullName": "BRB - BANCO DE BRASILIA S.A."
                  }
                ]
              }
            }
          }
        }
      }
    },
    "/banks/v1/{code}": {
      "get": {
        "tags": [
          "BANKS"
        ],
        "summary": "Busca as informações de um banco a partir de um código",
        "description": "",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "ispb": "00000000",
                  "name": "BCO DO BRASIL S.A.",
                  "code": 1,
                  "fullName": "Banco do Brasil S.A."
                }
              }
            }
          },
          "404": {
            "description": "O código do banco não foi encontrado",
            "content": {
              "application/json": {
                "example": {
                  "message": "Código bancário não encontrado",
                  "type": "BANK_CODE_NOT_FOUND"
                }
              }
            }
          }
        }
      }
    },
    "/cptec/v1/cidade": {
      "get": {
        "tags": [
          "CPTEC"
        ],
        "summary": "Listar localidades",
        "description": "Retorna listagem com todas as cidades junto a seus respectivos códigos presentes nos serviços da CPTEC.\nO Código destas cidades será utilizado para os serviços de meteorologia e a ondas (previsão oceânica) fornecido pelo centro.",
        "operationId": "listcities(/cptec/v1/cidade)",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {
              "Access-Control-Allow-Origin": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "*"
                  }
                }
              },
              "Access-Control-Allow-Credentials": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "true"
                  }
                }
              },
              "Cache-Control": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "max-age=0, s-maxage=86400, stale-while-revalidate, public"
                  }
                }
              },
              "Vary": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Accept-Encoding"
                  }
                }
              },
              "Content-Encoding": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "gzip"
                  }
                }
              },
              "Date": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Sun, 20 Dec 2020 16:07:19 GMT"
                  }
                }
              },
              "Connection": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "keep-alive"
                  }
                }
              },
              "Keep-Alive": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "timeout=5"
                  }
                }
              },
              "Transfer-Encoding": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "chunked"
                  }
                }
              }
            },
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/City"
                  }
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/cptec/v1/cidade/{cityName}": {
      "get": {
        "tags": [
          "CPTEC"
        ],
        "summary": "Buscar localidades",
        "description": "Retorna listagem com todas as cidades correspondentes ao termo pesquisado junto a seus respectivos códigos presentes nos serviços da CPTEC.\nO Código destas cidades será utilizado para os serviços de meteorologia e a ondas (previsão oceânica) fornecido pelo centro.",
        "operationId": "searchcities(/cptec/v1/cidade/:cityName)",
        "parameters": [
          {
            "name": "cityName",
            "in": "path",
            "description": "Nome ou parte do nome da cidade a ser buscada",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "Chiforímpola"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {
              "Access-Control-Allow-Origin": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "*"
                  }
                }
              },
              "Access-Control-Allow-Credentials": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "true"
                  }
                }
              },
              "Content-Length": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "295"
                  }
                }
              },
              "Vary": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Accept-Encoding"
                  }
                }
              },
              "Date": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Sun, 20 Dec 2020 16:08:27 GMT"
                  }
                }
              },
              "Connection": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "keep-alive"
                  }
                }
              },
              "Keep-Alive": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "timeout=5"
                  }
                }
              }
            },
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/City"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "message": "Nenhuma cidade não localizada",
                  "type": "NO_CITY_NOT_FOUND"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/cptec/v1/clima/capital": {
      "get": {
        "tags": [
          "CPTEC"
        ],
        "summary": "Condições atuais nas capitais",
        "description": "Retorna condições meteorológicas atuais nas capitais do país, com base nas estações de solo de seu aeroporto.",
        "operationId": "Condiçõesatuaisnascapitais(/cptec/v1/clima/capital)",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {
              "Access-Control-Allow-Origin": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "*"
                  }
                }
              },
              "Access-Control-Allow-Credentials": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "true"
                  }
                }
              },
              "Cache-Control": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "max-age=0, s-maxage=86400, stale-while-revalidate, public"
                  }
                }
              },
              "Vary": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Accept-Encoding"
                  }
                }
              },
              "Content-Encoding": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "gzip"
                  }
                }
              },
              "Date": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Sun, 27 Dec 2020 18:03:05 GMT"
                  }
                }
              },
              "Connection": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "keep-alive"
                  }
                }
              },
              "Transfer-Encoding": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "chunked"
                  }
                }
              }
            },
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/CurrentCondition"
                  }
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/cptec/v1/clima/aeroporto/{icaoCode}": {
      "get": {
        "tags": [
          "CPTEC"
        ],
        "summary": "Condições atuais nos aeroportos (/cptec/v1/clima/aeroporto/:icaoCode)",
        "description": "Retorna condições meteorológicas atuais no aeroporto solicitado. Este endpoint utiliza o código ICAO (4 dígitos) do aeroporto.",
        "operationId": "airportcurrentcondition(/cptec/v1/clima/aeroporto/:icaoCode)",
        "parameters": [
          {
            "name": "icaoCode",
            "in": "path",
            "description": "Código ICAO (4 dígitos) do aeroporto desejado",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "SBGR"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {
              "Access-Control-Allow-Origin": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "*"
                  }
                }
              },
              "Access-Control-Allow-Credentials": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "true"
                  }
                }
              },
              "Cache-Control": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "max-age=0, s-maxage=86400, stale-while-revalidate, public"
                  }
                }
              },
              "Content-Length": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "214"
                  }
                }
              },
              "Vary": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Accept-Encoding"
                  }
                }
              },
              "Date": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Sun, 27 Dec 2020 18:06:10 GMT"
                  }
                }
              },
              "Connection": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "keep-alive"
                  }
                }
              }
            },
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "$ref": "#/components/schemas/CurrentCondition"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "message": "Condições meteorológicas ou aeroporto não localizados",
                  "type": "AIRPORT_CONDITIONS_NOT_FOUND"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/cptec/v1/clima/previsao/{cityCode}": {
      "get": {
        "tags": [
          "CPTEC"
        ],
        "summary": "Previsão meteorológica para uma cidade",
        "description": "Retorna Pervisão meteorológica para 1 dia na cidade informada.",
        "operationId": "climapredictionwithoutdays(/cptec/v1/clima/previsao/:cityCode)",
        "parameters": [
          {
            "name": "cityCode",
            "in": "path",
            "description": "Código da cidade fornecido pelo endpoint /cidade",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "integer",
              "format": "int32",
              "example": 999
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {
              "Access-Control-Allow-Origin": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "*"
                  }
                }
              },
              "Access-Control-Allow-Credentials": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "true"
                  }
                }
              },
              "Cache-Control": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "max-age=0, s-maxage=86400, stale-while-revalidate, public"
                  }
                }
              },
              "Content-Length": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "196"
                  }
                }
              },
              "Vary": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Accept-Encoding"
                  }
                }
              },
              "Date": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Sun, 27 Dec 2020 18:13:24 GMT"
                  }
                }
              },
              "Connection": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "keep-alive"
                  }
                }
              }
            },
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "$ref": "#/components/schemas/climaPrediction"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "message": "Cidade não localizada",
                  "type": "CITY_NOT_FOUND"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/cptec/v1/clima/previsao/{cityCode}/{days}": {
      "get": {
        "tags": [
          "CPTEC"
        ],
        "summary": "Previsão meteorológica para, até, 14 dias",
        "description": "Retorna a previsão meteorológica para a cidade informada para um período de, até, 14 dias.",
        "operationId": "upto14daysprediction(/cptec/v1/clima/previsao/:cityCode/:days)",
        "parameters": [
          {
            "name": "cityCode",
            "in": "path",
            "description": "Código da cidade fornecido pelo endpoint /cidade",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "integer",
              "format": "int32",
              "example": 999
            }
          },
          {
            "name": "days",
            "in": "path",
            "description": "Quantidade de dias desejado para a previsão",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "integer",
              "format": "int32",
              "example": 5
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {
              "Access-Control-Allow-Origin": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "*"
                  }
                }
              },
              "Access-Control-Allow-Credentials": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "true"
                  }
                }
              },
              "Cache-Control": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "max-age=0, s-maxage=86400, stale-while-revalidate, public"
                  }
                }
              },
              "Content-Length": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "666"
                  }
                }
              },
              "Vary": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Accept-Encoding"
                  }
                }
              },
              "Date": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Sun, 27 Dec 2020 18:03:47 GMT"
                  }
                }
              },
              "Connection": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "keep-alive"
                  }
                }
              }
            },
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "$ref": "#/components/schemas/climaPrediction"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/cptec/v1/ondas/{cityCode}": {
      "get": {
        "tags": [
          "CPTEC"
        ],
        "summary": "Previsão oceânica",
        "description": "Retorna a previsão oceÇanica para a cidade informada para um dia",
        "operationId": "ondaspredictionwithoutdays(/cptec/v1/ondas/:cityCode)",
        "parameters": [
          {
            "name": "cityCode",
            "in": "path",
            "description": "Código da cidade fornecido pelo endpoint /cidade",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "integer",
              "format": "int32",
              "example": 241
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {
              "Access-Control-Allow-Origin": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "*"
                  }
                }
              },
              "Access-Control-Allow-Credentials": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "true"
                  }
                }
              },
              "Cache-Control": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "max-age=0, s-maxage=86400, stale-while-revalidate, public"
                  }
                }
              },
              "Vary": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Accept-Encoding"
                  }
                }
              },
              "Content-Encoding": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "gzip"
                  }
                }
              },
              "Date": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Sun, 27 Dec 2020 18:04:18 GMT"
                  }
                }
              },
              "Connection": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "keep-alive"
                  }
                }
              },
              "Transfer-Encoding": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "chunked"
                  }
                }
              }
            },
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "$ref": "#/components/schemas/ondasPrediction"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/cptec/v1/ondas/{cityCode}/{days}": {
      "get": {
        "tags": [
          "CPTEC"
        ],
        "summary": "Previsão oceânica para, até, 6 dias",
        "description": "Retorna a previsão oceânica para a cidade informada para um período de, até, 6 dias.",
        "operationId": "ondaspredictionupto6days(/cptec/v1/ondas/:cityCode/:days)",
        "parameters": [
          {
            "name": "cityCode",
            "in": "path",
            "description": "Código da cidade fornecido pelo endpoint /cidade",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "integer",
              "format": "int32",
              "example": 241
            }
          },
          {
            "name": "days",
            "in": "path",
            "description": "Quantidade de dias desejada para a previsão",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "integer",
              "format": "int32",
              "example": 2
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {
              "Access-Control-Allow-Origin": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "*"
                  }
                }
              },
              "Access-Control-Allow-Credentials": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "true"
                  }
                }
              },
              "Cache-Control": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "max-age=0, s-maxage=86400, stale-while-revalidate, public"
                  }
                }
              },
              "Vary": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Accept-Encoding"
                  }
                }
              },
              "Content-Encoding": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "gzip"
                  }
                }
              },
              "Date": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "Sun, 27 Dec 2020 18:04:45 GMT"
                  }
                }
              },
              "Connection": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "keep-alive"
                  }
                }
              },
              "Transfer-Encoding": {
                "content": {
                  "text/plain": {
                    "schema": {
                      "type": "string"
                    },
                    "example": "chunked"
                  }
                }
              }
            },
            "content": {
              "application/json; charset=utf-8": {
                "schema": {
                  "$ref": "#/components/schemas/ondasPrediction"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "message": "Quantidade de dias inválida (mínimo 1 dia e máximo 6 dias)",
                  "type": "INVALID_NUMBER_OF_DAYS"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMessage"
                },
                "example": {
                  "message": "Cidade não localizada",
                  "type": "CITY_NOT_FOUND"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/feriados/v1/{ano}": {
      "get": {
        "tags": [
          "Feriados nacionais"
        ],
        "summary": "Lista os feriados nacionais de determinado ano.",
        "description": "Calcula os feriados móveis baseados na Páscoa e adiciona os feriados fixos",
        "parameters": [
          {
            "name": "ano",
            "description": "Ano para calcular os feriados.\n",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": [
                  {
                    "date": "2021-01-01",
                    "name": "Confraternização mundial",
                    "type": "national"
                  },
                  {
                    "date": "2021-02-16",
                    "name": "Carnaval",
                    "type": "national"
                  },
                  {
                    "date": "2021-04-02",
                    "name": "Paixão de Cristo",
                    "type": "national"
                  },
                  {
                    "date": "2021-04-04",
                    "name": "Páscoa",
                    "type": "national"
                  },
                  {
                    "date": "2021-04-21",
                    "name": "Tiradentes",
                    "type": "national"
                  },
                  {
                    "date": "2021-05-01",
                    "name": "Dia do trabalho",
                    "type": "national"
                  },
                  {
                    "date": "2021-06-03",
                    "name": "Corpus Christi",
                    "type": "national"
                  },
                  {
                    "date": "2021-09-07",
                    "name": "Independência do Brasil",
                    "type": "national"
                  },
                  {
                    "date": "2021-10-12",
                    "name": "Nossa Senhora Aparecida",
                    "type": "national"
                  },
                  {
                    "date": "2021-11-02",
                    "name": "Finados",
                    "type": "national"
                  },
                  {
                    "date": "2021-11-15",
                    "name": "Proclamação da República",
                    "type": "national"
                  },
                  {
                    "date": "2021-12-25",
                    "name": "Natal",
                    "type": "national"
                  }
                ]
              }
            }
          },
          "404": {
            "description": "Ano fora do intervalo suportado.",
            "content": {
              "application/json": {
                "example": {
                  "type": "feriados_range_error",
                  "message": "Ano fora do intervalo suportado entre 1900 e 2199."
                }
              }
            }
          },
          "500": {
            "description": "Erro inesperado.",
            "content": {
              "application/json": {
                "example": {
                  "type": "feriados_error",
                  "message": "Erro ao calcular feriados."
                }
              }
            }
          }
        }
      }
    },
    "/ibge/uf/v1": {
      "get": {
        "tags": [
          "IBGE"
        ],
        "summary": "Retorna informações de todos estados do Brasil",
        "description": "",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 11,
                    "sigla": "RO",
                    "nome": "Rondônia",
                    "regiao": {
                      "id": 1,
                      "sigla": "N",
                      "nome": "Norte"
                    }
                  },
                  {
                    "id": 12,
                    "sigla": "AC",
                    "nome": "Acre",
                    "regiao": {
                      "id": 1,
                      "sigla": "N",
                      "nome": "Norte"
                    }
                  }
                ]
              }
            }
          }
        }
      }
    },
    "/ibge/uf/v1/{code}": {
      "get": {
        "tags": [
          "IBGE"
        ],
        "summary": "Busca as informações de um um estado a partir da sigla ou código",
        "description": "",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "id": 35,
                  "sigla": "SP",
                  "nome": "São Paulo",
                  "regiao": {
                    "id": 3,
                    "sigla": "SE",
                    "nome": "Sudeste"
                  }
                }
              }
            }
          },
          "404": {
            "description": "O código / sigla do estado não foi encontrado",
            "content": {
              "application/json": {
                "example": {
                  "name": "NotFoundError",
                  "message": "UF não encontrado",
                  "type": "not_found"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "City": {
        "title": "City",
        "required": [
          "name",
          "state",
          "code"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "code": {
            "type": "string"
          }
        },
        "example": {
          "name": "São Benedito",
          "state": "CE",
          "code": "4750"
        }
      },
      "CurrentCondition": {
        "title": "CurrentCondition",
        "required": [
          "icao_code",
          "last_update",
          "pressure",
          "visibility",
          "wind",
          "wind_direction",
          "humidity",
          "clima_code",
          "clima_desc",
          "temp"
        ],
        "type": "object",
        "properties": {
          "icao_code": {
            "type": "string"
          },
          "last_update": {
            "type": "string"
          },
          "pressure": {
            "type": "string"
          },
          "visibility": {
            "type": "string"
          },
          "wind": {
            "type": "string"
          },
          "wind_direction": {
            "type": "string"
          },
          "humidity": {
            "type": "string"
          },
          "clima_code": {
            "type": "string"
          },
          "clima_desc": {
            "type": "string"
          },
          "temp": {
            "type": "string"
          }
        },
        "example": {
          "icao_code": "SBAR",
          "last_update": "2021-01-27T15:00:00.974Z",
          "pressure": "1014",
          "visibility": "9000",
          "wind": "29",
          "wind_direction": "90",
          "humidity": "74",
          "clima_code": "ps",
          "clima_desc": "Predomínio de Sol",
          "temp": "28"
        }
      },
      "climaPrediction": {
        "title": "climaPrediction",
        "required": [
          "city_name",
          "state",
          "last_update",
          "clima"
        ],
        "type": "object",
        "properties": {
          "city_name": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "last_update": {
            "type": "string"
          },
          "clima": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/clima"
            },
            "description": ""
          }
        },
        "example": {
          "city_name": "Brejo Alegre",
          "state": "SP",
          "last_update": "2020-12-27",
          "clima": [
            {
              "date": "2020-12-27",
              "condition": "pc",
              "min": "20",
              "max": "30",
              "uv_index": "13.0",
              "condition_desc": "Pancadas de Chuva"
            },
            {
              "date": "2020-12-28",
              "condition": "pc",
              "min": "22",
              "max": "29",
              "uv_index": "13.0",
              "condition_desc": "Pancadas de Chuva"
            }
          ]
        }
      },
      "clima": {
        "title": "clima",
        "required": [
          "date",
          "condition",
          "min",
          "max",
          "uv_index",
          "condition_desc"
        ],
        "type": "object",
        "properties": {
          "date": {
            "type": "string"
          },
          "condition": {
            "type": "string"
          },
          "min": {
            "type": "string"
          },
          "max": {
            "type": "string"
          },
          "uv_index": {
            "type": "string"
          },
          "condition_desc": {
            "type": "string"
          }
        },
        "example": {
          "date": "2020-12-27",
          "condition": "pc",
          "min": "20",
          "max": "30",
          "uv_index": "13.0",
          "condition_desc": "Pancadas de Chuva"
        }
      },
      "ondasPrediction": {
        "title": "ondasPrediction",
        "required": [
          "city_name",
          "state",
          "last_update",
          "ondas"
        ],
        "type": "object",
        "properties": {
          "city_name": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "last_update": {
            "type": "string"
          },
          "ondas": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ondasDate"
            },
            "description": ""
          }
        },
        "example": {
          "city_name": "Rio de Janeiro",
          "state": "RJ",
          "last_update": "2020-12-27",
          "ondas": [
            {
              "date": "27-12-2020",
              "ondas_data": [
                {
                  "wind": "5.2",
                  "wind_direction": "E",
                  "wave_height": "0.8",
                  "wave_direction": "ESE",
                  "agitation": "Fraco",
                  "hour": "00h Z"
                },
                {
                  "wind": "4.1",
                  "wind_direction": "ENE",
                  "wave_height": "0.8",
                  "wave_direction": "ESE",
                  "agitation": "Fraco",
                  "hour": "03h Z"
                }
              ]
            }
          ]
        }
      },
      "ondasDate": {
        "title": "ondasDate",
        "required": [
          "date",
          "ondas_data"
        ],
        "type": "object",
        "properties": {
          "date": {
            "type": "string"
          },
          "ondas_data": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ondas"
            },
            "description": ""
          }
        },
        "example": {
          "date": "27-12-2020",
          "ondas_data": [
            {
              "wind": "5.2",
              "wind_direction": "E",
              "wave_height": "0.8",
              "wave_direction": "ESE",
              "agitation": "Fraco",
              "hour": "00h Z"
            },
            {
              "wind": "4.1",
              "wind_direction": "ENE",
              "wave_height": "0.8",
              "wave_direction": "ESE",
              "agitation": "Fraco",
              "hour": "03h Z"
            }
          ]
        }
      },
      "ondas": {
        "title": "ondas",
        "required": [
          "wind",
          "wind_direction",
          "wave_height",
          "wave_direction",
          "agitation",
          "hour"
        ],
        "type": "object",
        "properties": {
          "wind": {
            "type": "string"
          },
          "wind_direction": {
            "type": "string"
          },
          "wave_height": {
            "type": "string"
          },
          "wave_direction": {
            "type": "string"
          },
          "agitation": {
            "type": "string"
          },
          "hour": {
            "type": "string"
          }
        },
        "example": {
          "wind": "5.2",
          "wind_direction": "E",
          "wave_height": "0.8",
          "wave_direction": "ESE",
          "agitation": "Fraco",
          "hour": "00h Z"
        }
      },
      "ErrorMessage": {
        "title": "ErrorMessage",
        "required": [
          "message",
          "type"
        ],
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          },
          "type": {
            "type": "string"
          }
        },
        "example": {
          "message": "Cidade não localizada",
          "type": "CITY_NOT_FOUND"
        }
      }
    }
  }
}
